BrokkAi/brokk

- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/io/github/jbellis/brokk/Analyzer.scala
- src/main/scala/io/github/jbellis/brokk/CodeUnit.scala
- src/main/scala/io/github/jbellis/brokk/IAnalyzer.scala
- src/main/scala/io/github/jbellis/brokk/Language.scala
* add sbt build
* split analyzer into small files
* several import optimize
> feat: add sbt build

- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/GuiTheme.java
- before it only used light theme at startup because project wasn't initialized (and it could not load workspace props)
- before changes to the theme aren't saved because of the order problem
- Now I tested it multiple times and it worked for me like expected
> fix: ensure theme is properly saved and applied on startup

- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/PreviewPanel.java
... otherwise the preview window is white in dark mode
> feat: Add theming to preview windows

- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
> fix: ensure proper resizing behavior for history split pane components

- README.md
- jbang-catalog.json
brokk is fun to play with - thought I would make it easy to run.
I didn't find a maven artifact or some stable named jar release so for now when doing release the .jar reference will need updating at release.
> feat: make it easy to run brokk

- src/main/java/io/github/jbellis/brokk/ContextFragment.java
- src/main/java/io/github/jbellis/brokk/IConsoleIO.java
- src/main/java/io/github/jbellis/brokk/SessionResult.java
- src/main/java/io/github/jbellis/brokk/agents/CodeAgent.java
- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
- src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/AIMessageRenderer.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/BaseChatMessagePanel.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/CustomMessageRenderer.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/MarkdownRenderUtil.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/MessageComponentRenderer.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/ThemeColors.java
- src/main/java/io/github/jbellis/brokk/gui/MOP/UserMessageRenderer.java
- src/main/java/io/github/jbellis/brokk/gui/MarkdownOutputPanel.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
> Feat/improve chat UI

- .gitignore
- README.md
- build.sbt
Just a couple of minor changes to the build
> Build improvements

- src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
> fix: Improve commit table row selection independent of the theme

- src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java
I restarted this as master changed the UI and made it difficult to do a regular merge
Here we return the fields to the build tab.
the languages CDL was changed as suggested and it is now a separate dialog box
https://github.com/user-attachments/assets/bef4f5ad-2bc9-4c51-be2b-2d838799b3fd
https://github.com/user-attachments/assets/0664b163-3cd2-4084-bd4f-36749901fcad
> Rerun build take 2

- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
Live version of the file was shown instead of the selected revision.
> fix: Capturing old revisions is broken

- src/main/java/io/github/jbellis/brokk/gui/dialogs/MultiFileSelectionDialog.java
> enh: Add back autocomplete instructions

- src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
- src/main/java/io/github/jbellis/brokk/gui/GitUiUtil.java
- src/test/java/io/github/jbellis/brokk/git/InMemoryRepo.java
> feat: Add "Capture Diff vs $branch" right-click option to branches table

- src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
> enh: move Git Log Search into a text field

- src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
> fix: Cannot open MOP in a new window while the output is being generated

- README.md
- src/main/java/io/github/jbellis/brokk/gui/SwingIconUtil.java
- src/main/java/io/github/jbellis/brokk/gui/SwingUtil.java
- src/main/java/io/github/jbellis/brokk/gui/mop/MarkdownOutputPanel.java
- src/main/java/io/github/jbellis/brokk/gui/mop/MessageBubble.java
- src/main/java/io/github/jbellis/brokk/gui/mop/stream/blocks/CodeBlockComponentData.java
This partially fixes  #130 
It uses icons instead of emojis, the results are below and should be system independent
A utility was created to display icons such that it is easier to select one
there are more places where emojis are used, but the current selection is very limited. some alternatives can be checked like:
github.com/kordamp/ikonli
> Fix visual bug

- src/main/java/io/github/jbellis/brokk/gui/FilterBox.java
- src/main/java/io/github/jbellis/brokk/gui/GitIssuesTab.java
- src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
Fixed #184 and I also improved the alignment to fix #161:
https://github.com/user-attachments/assets/327305a0-cb87-4df3-9f0d-0af502484248
> Fix remove filters

- src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsProjectPanel.java
> fix: NPE on data retention policy

- src/main/java/io/github/jbellis/brokk/gui/mop/stream/TextNodeMarkerCustomizer.java
- src/test/java/io/github/jbellis/brokk/gui/mop/stream/TextNodeMarkerCustomizerTest.java
fixes #159 
code blocks were ignored before
> refactor: Remove skip tags and add tests for highlighting inside them

- src/main/java/io/github/jbellis/brokk/gui/FilterBox.java
- src/main/java/io/github/jbellis/brokk/gui/GitIssuesTab.java
- src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
- src/main/java/io/github/jbellis/brokk/gui/mop/ThemeColors.java
Fixes #187 
it also fixes the aligment of the controls and other labels around it. The filter box is also ThemeAware for dynamic theme changes
> Fix filter box colors

- src/main/java/io/github/jbellis/brokk/util/Environment.java
> fix: Stop button doesn’t work during test execution (Code Agent)

- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/agents/CodeAgent.java
> enh: Clear code blocks out of taskMessage history

- src/main/java/io/github/jbellis/brokk/Brokk.java
- src/main/java/io/github/jbellis/brokk/gui/GuiTheme.java
> fix: Theme changes only apply to one window

- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
> enh: Capture on output window

- .github/workflows/ci.yml
- src/test/java/io/github/jbellis/brokk/gui/mop/TestUtil.java
Initial pass, this will likely require some tweaking
> chore: setup continuous integration for PR and new commits

- docs/litellm.md
- src/main/java/io/github/jbellis/brokk/Llm.java
- src/test/java/io/github/jbellis/brokk/GeminiThinkingTest.java
- src/test/java/io/github/jbellis/brokk/gui/mop/TestUtil.java
> Llm error using liteltm and gemini

- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/context/Context.java
- src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/SessionsDialog.java
- src/main/java/io/github/jbellis/brokk/util/HistoryIo.java
> fix: renaming sessions shouldn't be subject to interruption by Stop action

- src/main/java/io/github/jbellis/brokk/gui/GitCommitTab.java
Just makes the button un usable while waiting for Brokk to suggest a message to the user. LLMs also added more error reporting to the user, as they have a tendency to do. If this is undesirable it can be removed, but it is left in the diff for now.
> fix/179 Disable suggest message button until message has arrived

- src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
- src/main/java/io/github/jbellis/brokk/difftool/ui/FileComparison.java
- src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
> feat: Improve PR diff functionality

- src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
- src/main/java/io/github/jbellis/brokk/difftool/ui/BufferDiffPanel.java
This pull request enhances the Brokk Diff Tool to support dynamic theming and improves the layout of the search bars.
Key changes:
*   **Theming Support:** `BrokkDiffPanel` now implements the `ThemeAware` interface. This allows the panel and its child components to update their appearance when the application theme changes. The `applyTheme` method iterates through cached panels and updates the UI of all child components.
*   **Search Bar Layout:** The `BufferDiffPanel`'s layout has been refactored to use `BorderLayout` instead of `JSplitPane`. The search bars are now positioned at the top of the panel, and the file panels are in the center. The search bars are aligned with the text areas below using a `FormLayout`.
*   **Search Bar Alignment:** The search bars are now aligned with the …
> Brokk Diff Tool: dynamic theming, improved search bar layout and alignment

- src/main/java/io/github/jbellis/brokk/gui/search/GenericSearchBar.java
> feat(ui): add clear button to search box

- .brokk/review.md
- .gitignore
- .idea/scala_compiler.xml
- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/IProject.java
- src/main/java/io/github/jbellis/brokk/MainProject.java
- src/main/java/io/github/jbellis/brokk/WorktreeProject.java
- src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
- src/main/java/io/github/jbellis/brokk/gui/GitUiUtil.java
- src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsProjectPanel.java
> feat: add Capture button to PR actions

- src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
This pull request adds a context menu to the remote branches table in the Git log tab, providing several new actions.
Key changes:
*   **Context Menu:** A right-click context menu is added to the remote branch table.
*   **Menu Items:** The context menu includes "Checkout", "New Branch From This", and "Capture Diff vs Branch" options.
*   **Action Handlers:**  Clicking "Checkout" checks out the selected remote branch. "New Branch From This" creates a new local branch tracking the selected remote branch. "Capture Diff vs Branch" shows the diff between the current branch and the selected remote branch.
*   **UI Enhancements:** The remote branch table now uses `ListSelectionModel.SINGLE_SELECTION` for better usability.
*   **Error Handling:** Includes basic error handling for the diff …
> Adds context menu to remote branches table with checkout and diff actions

- src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
> enh: Checkout button in PR tab should preserve branch names

- src/main/java/io/github/jbellis/brokk/git/GitRepo.java
- src/main/java/io/github/jbellis/brokk/git/GitWorkflowService.java
- src/main/java/io/github/jbellis/brokk/gui/GitCommitBrowserPanel.java
- src/main/java/io/github/jbellis/brokk/gui/GitCommitTab.java
**Intent:**  
Refactor Git operations to centralize logic in a new `GitWorkflowService` class, improving maintainability, error handling, and integration with the UI. This addresses inconsistencies in branch handling and enhances user feedback for actions like commit, push, and pull.
**Behavior Changes:**  
- Git operations (e.g., commit, push, pull) now use `GitWorkflowService`, preventing actions on invalid branches (e.g., remote or synthetic ones).  
- Commit message suggestions leverage LLM for diff analysis, with fallbacks for empty messages.  
- UI panels (e.g., `GitCommitBrowserPanel`) dynamically enable/disable buttons based on branch type and state, providing clearer tooltips and error messages.
- Introduced `GitWorkflowService` with methods for …
> Refactors Git operations into `GitWorkflowService` for improved maintainability and UI integration

- src/main/java/io/github/jbellis/brokk/git/GitWorkflowService.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/CreatePullRequestDialog.java
**Intent:** extract functionality from the CreatePullRequestDaiog
**Behavior Changes:**
- extract functionality from the CreatePullRequestDaiog (for reuse throught the architect)
- Added new methods in GitWorkflowService for computing branch differences, suggesting PR details, and directly creating PRs on GitHub, including branch pushing.
> Extract functionality from the CreatePullRequestDaiog

- src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
The esc hotkey for leaving the search bar already exists, so the only change needed for this issue is this one.
> feature: added esc hotkey for getting out of diffs

- src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
- src/main/java/io/github/jbellis/brokk/difftool/ui/BufferDiffPanel.java
- src/main/java/io/github/jbellis/brokk/difftool/ui/FilePanel.java
- src/test/java/io/github/jbellis/brokk/difftool/ui/DocumentSyncTest.java
- src/test/java/io/github/jbellis/brokk/difftool/ui/FilePanelDocumentSyncTest.java
- src/test/java/io/github/jbellis/brokk/difftool/ui/HybridDocumentSyncTest.java
feat: Implement hybrid document sync to prevent line joining bug
feat: Add "Save All" button and unsaved changes handling
feat: Update save button text and enable state
as suggested on:
https://github.com/BrokkAi/brokk/pull/372#issuecomment-3024265035
> fix/diff-auto-save: Don't autosave on diff, instead add a save/save all button

- src/main/scala/io/github/jbellis/brokk/analyzer/CppAnalyzer.scala
- src/main/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzer.scala
- src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala
* Removed unnecessary passes such as CFG and DDG.
* The resulting CPG is essentially an AST + type hierarchy + call graph
Unit tests look good on my side.
I additionally formatted the code on the IDE, but something like `scalafmt` would help keep things consistent.
Resolves https://github.com/BrokkAi/brokk/issues/387
> Remove Unnecessary CPG Passes

- src/main/java/io/github/jbellis/brokk/AbstractProject.java
- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/IProject.java
- src/main/java/io/github/jbellis/brokk/MainProject.java
- src/main/java/io/github/jbellis/brokk/SessionManager.java
- src/main/java/io/github/jbellis/brokk/WorktreeProject.java
- src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
- src/main/java/io/github/jbellis/brokk/gui/dialogs/SessionsDialog.java
- src/main/java/io/github/jbellis/brokk/util/SerialByKeyExecutor.java
- src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
- src/test/java/io/github/jbellis/brokk/util/SerialByKeyExecutorTest.java
> fix: Corrupt Session zip file

- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/SessionManager.java
> enh: Reuse existing empty session instead of creating a new one

- src/main/java/io/github/jbellis/brokk/ContextManager.java
- src/main/java/io/github/jbellis/brokk/SessionManager.java
- src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
> fix: Fatal session read error

- .github/workflows/ci.yml
- src/main/java/io/github/jbellis/brokk/analyzer/Language.java
- src/main/java/io/github/jbellis/brokk/analyzer/NodeJsDependencyHelper.java
- src/test/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzerTest.java
**Intent:**  
This PR refactors shared dependency management logic for JavaScript and TypeScript analyzers to reduce duplication and enhance maintainability. It also updates the CI workflow to run on all branches, improving testing coverage.
**Behaviour Changes:**  
- CI pipelines now trigger on any branch (e.g., push or pull requests to '**'), rather than just 'master', ensuring broader automated testing.  
- JavaScript and TypeScript languages use a new helper class for scanning node_modules dependencies and checking if paths are analyzed, resulting in more consistent handling of Node.js ecosystems.
- Extracted common Node.js logic into a new utility class, NodeJsDependencyHelper.java, to handle dependency candidates and analysis checks.  
- Updated …
> Support to import dependencies in typescript

- app/src/main/java/io/github/jbellis/brokk/AnalyzerWrapper.java
> fix: AnalyzerWrapper's WatchService is not triggering correctly for external git events

- app/build.gradle.kts
- app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
- app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java
- app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- gradle/libs.versions.toml
Using our build of error-prone that includes `RedundantNullCheck`.
> fix: Use local error-prone lib

- app/src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
Issue #436 requested that renaming a branch happen directly in the table cell instead of opening a separate dialog.  This commit delivers that UX improvement.
Key points
----------
* Replace the anonymous DefaultTableModel with a LocalBranchTableModel that: • marks column-1 (“Branch”) editable (but not the virtual “stashes” row) • overrides setValueAt() to call GitRepo.renameBranch(old, new) via ContextManager.submitUserTask, giving an optimistic UI update and then refreshing the whole view on success or failure.
* Set `branchTable.setSurrendersFocusOnKeystroke(true)` so users can start editing by typing.
* Change the “Rename” context-menu action to start cell editing instead of popping up a JOptionPane dialog.
* Remove the now-unused renameBranch dialog helper.
The rest of the branch, …
> enh/GitLogTab: enable inline branch rename in the Local Branches table

- app/src/main/java/io/github/jbellis/brokk/Service.java
> enh: Add ability to easily customize a model

- app/src/main/java/io/github/jbellis/brokk/IConsoleIO.java
- app/src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
- app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
> fix: Pass JFrame to showConfirmDialog in BrokkDiffPanel

- app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
**What changed?**  
- Convert user-supplied exclusions into `Set<Path>` (normalized, absolute).  
- Replace `excludedFiles.contains(...)` (exact-string match) with  
```java
excludedPaths.stream().anyMatch(filePath::startsWith)
```  
so any file under an excluded directory is skipped.  
- Leave the existing “only these extensions” check intact.
**Why?**  
Previously “app/mop” only excluded that exact path, not its children. Now `startsWith` gives true directory semantics without breaking single-file exclusions.
> Support directory-wide exclusions in `TreeSitterAnalyzer`

- joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzer.scala
- joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/PruneTypesPass.scala
- joern-analyzers/src/test/resources/testcode-java/XExtendsY.java
- joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzerTest.scala
* Skeleton checks base type decls and attempts to sort them by interfaces/classes
* Fix pruning that doesn't consider inheritance a reference
> [0.12] Joern Java Analyzer Skeleton Supports Inheritance

- app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
> Badges in Workspace Panel Share Row with Desc

- .brokk/project.properties
- app/src/main/java/io/github/jbellis/brokk/Completions.java
- app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java
- app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
**Intent:**  
Improve code completion reliability and user experience in the Brokk tool by adding safeguards against errors, enhancing autocomplete features, and refining input handling to prevent overloads and ensure responsive suggestions.
**Behavior Changes:**  
- Autocomplete now requires at least 2 characters of input to trigger, reducing unnecessary searches and improving performance.  
- Symbol and file completions in the instructions panel are limited to 50-100 results, with caching to speed up repeats.  
- Context suggestions use debounced timers (100-1000ms delays) for bulk changes or typing, making the interface less jittery.  
- Exception handling in symbol searches logs warnings and falls back to safer defaults, preventing crashes.
- Integrated …
> Improved code completion with safeguards, performance, and user experience enhancements

- app/src/main/java/io/github/jbellis/brokk/tools/ToolRegistry.java
- Intent: register a set of tools/actions for file and workspace management and git-commit search so they can be displayed and resolved by name throughout the Search Agent
> Register missing tools used by SearchAgent

- app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
- app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java
Improved the reliability of source code extraction and the range finding within trees.
> JDT: More Reliable Source Code Handling

- app/src/main/java/io/github/jbellis/brokk/gui/GitCommitBrowserPanel.java
> fix: Create PR button in GLP doesn't enable until restart

- app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Side bar remembers size before minimized so that it maximizes to that width again.
https://github.com/user-attachments/assets/517ea618-4423-46b7-aed8-4f83d1549fc8
> Side Panel Maximizes to Remembered Size

- app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- using a standard jbutton now, removed the custom component
> refactor: Simplify InstructionsPanel Plan Options button

- app/src/main/java/io/github/jbellis/brokk/gui/dialogs/MultiFileSelectionDialog.java
* Removes the `isCpg` check to enable class summaries
* Fix the auto-complete functionality of the class search
> Enable Class Summaries + Fix Auto-Complete

- app/src/main/java/io/github/jbellis/brokk/analyzer/JdtAnalyzer.java
- app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
- app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
* Fixed path of nested classes when asked for usages
* Normalized constructor path finding as just the class, which in JDT, gives constructor classes and handles implicit constructors
> Fix Usages of Nested Class Constructors

- app/src/main/java/io/github/jbellis/brokk/Brokk.java
- app/src/main/java/io/github/jbellis/brokk/ContextManager.java
- app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
> [Feature]: when closing project window, add confirm dialog if an active (AI) task is in progress

- app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- shrunk history down a lot
- reusing split buttons for branch and history now
- can change or create branches from the instruction panel
> Show git branch in title

- app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ArchitectOptionsDialog.java
Allows users a shortcut to configuring MCP servers from the Plan Options Dialog
https://github.com/user-attachments/assets/a550c61e-80e8-4319-a43c-4335503977cd
> Add "Configure" Button when MCP Servers are Empty

- app/src/main/java/io/github/jbellis/brokk/Brokk.java
- app/src/main/java/io/github/jbellis/brokk/MainProject.java
- app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsGlobalPanel.java
- adds new startup panel to settings to change behavior between old behavior (all projects that were open) to new (only last project)
- default is last project opened
> feat: Add startup behavior settings and open mode options

- app/src/main/java/io/github/jbellis/brokk/agents/SearchAgent.java
- app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
- app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
- renames answer to ask (no one seems to like answer and ask is commonplace in other ai editors)
- default to ask + search mode
> 1080 feature default to answer action and rename it

- app/src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
- app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SessionsDialog.java
- **UI: Adjust padding in HistoryOutputPanel and SessionsDialog**
- **refactor: Remove unnecessary blank lines in SessionsDialog.java**
> 1040 bug output activity alignment

- app/src/main/java/io/github/jbellis/brokk/ContextManager.java
- app/src/main/java/io/github/jbellis/brokk/SessionRegistry.java
> fix: [Bug]: confusing open-in-new-window message

- app/src/main/java/io/github/jbellis/brokk/agents/SearchAgent.java
fix #1174
- Intent: avoid running duplicate-detection (and its signature extraction) on terminal tool requests that don't have a list parameter and can throw or be mis-handled when deduped.
- Behavior changes: terminal tools ("answer", "createTaskList", "workspaceComplete", "abortSearch") are now detected up-front and returned immediately (single-item list). Only when no terminal tool is present do we run the existing dedupe/forge logic across requests.
- Key implementation ideas:
- Reordered logic to first scan response.toolExecutionRequests() for any terminal tool and short-circuit if found.
- Moved the handleDuplicateRequestIfNeeded mapping to run only for non-terminator flows.
- Added explanatory comments and simplified control flow to make intent explicit and prevent …
> fix: avoid duplicate detection on terminator tool requests; short-circuit if found

- app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
- **enh: Augment task prompt with overall goal and task list**
- **refactor: Improve task list summarization in TaskListPanel**
the task list is thrown into a summarizer prompt using the search model to provide a goal.
The goal, the tasklisk (with order being applied), which number of the task the architect is executing followed by the task text
```md
<goal>
Improve project usability, documentation, and code maintainability.
Ordered task list:
1. add a readme.md to this project
2. add a gradle execute task to this project
3. comment the code in the epubreader
You are executing task 2 of 3.
add a gradle execute task to this project
</goal>
```
> Feature: improve context sent to architect with tasks

- app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
Opts to update files based on a "last update" interval instead of using (expensive) content hashing strategy to detect changes. This should improve start time, I'm observing about 0.5-1s improvement for Java.
Another bonus is one fewer hash map to track.
> TreeSitter Updates Use `mtime` Instead of Hashes

- app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java
> fix: [Bug]: initializing git repo when opening a project does not result in a GitRepo reference in the Project

- app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
- app/src/test/java/io/github/jbellis/brokk/gui/terminal/TaskListPanelTest.java
we just now look for editable fragments
extracted out methods and added testing
> no search on first task

- app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
didn't push the commit in the last PR
> logging trace on git repo changes
