src/main/java/io/github/jbellis/brokk/ContextManager.java
It is always only showing "pasted content" as the content.
=> fix: pasting of snippets not working

src/main/java/io/github/jbellis/brokk/ContextManager.java, src/main/java/io/github/jbellis/brokk/gui/MenuBar.java
I got an exception changing the autosummaries count when the autosummaries are still in place:
Changed it to follow the worker pattern to not been called from the EDT thread.
```java
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Never call blocking get() from EDT
at io.github.jbellis.brokk.AnalyzerWrapper.get(AnalyzerWrapper.java:379)
at io.github.jbellis.brokk.AnalyzerWrapper.get(AnalyzerWrapper.java:404)
at io.github.jbellis.brokk.Context.lambda$buildAutoContext$7(Context.java:316)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemainin …
```
=> fix: Add asynchronous method for setting auto-context file count

src/main/java/io/github/jbellis/brokk/Project.java, src/main/java/io/github/jbellis/brokk/gui/Chrome.java, src/main/java/io/github/jbellis/brokk/gui/GuiTheme.java, src/main/java/io/github/jbellis/brokk/gui/MenuBar.java
- On the fly switch between Bright/Dark Theme.
- Persisted in Project.Properties
- central manager GuiTheme class
=> feat: Add light and dark theme support

src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Set a default spliter position so that new opened Projects does not have collapsed top area above instructions
=> fix: Set reasonable default for vertical split pane

src/main/java/io/github/jbellis/brokk/gui/MarkdownOutputPanel.java
fixes #34 
we need to force the Sub-Components (HtmlPane, RSyntaxTextArea, ...) to not scroll to the end on updates on their content
SmartScroll is interpreting this as the user scolled to the bottom/end
=> Fix SmartScroll

src/main/java/io/github/jbellis/brokk/Coder.java, src/main/java/io/github/jbellis/brokk/ContextFragment.java, src/main/java/io/github/jbellis/brokk/ContextManager.java, src/main/java/io/github/jbellis/brokk/EditBlock.java, src/main/java/io/github/jbellis/brokk/IConsoleIO.java, src/main/java/io/github/jbellis/brokk/Models.java, src/main/java/io/github/jbellis/brokk/SessionResult.java, src/main/java/io/github/jbellis/brokk/agents/CodeAgent.java, src/main/java/io/github/jbellis/brokk/gui/Chrome.java, src/main/java/io/github/jbellis/brokk/gui/ContextPanel.java, src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java, src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java, src/main/java/io/github/jbellis/brokk/gui/MarkdownOutputPanel.java, src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java, src/test/java/io/github/jbellis/brokk/CoderTest.java, src/test/java/io/github/jbellis/brokk/EditBlockTest.java
This PR introduces a significant refactoring of how output (LLM responses, system messages, command results, etc.) is handled and displayed throughout the application.
**Core Change:**
The primary change is moving away from representing and passing output as raw `String` objects. Instead, the system now uses structured `dev.langchain4j.data.message.ChatMessage` objects (including `UserMessage`, `AiMessage`, `CustomMessage`) and `TaskEntry` lists.
**Key Impacts & Benefits:**
*   **Richer Representation:** Using `ChatMessage` allows the system to understand the *type* of output (AI, User, System, Tool, Build Error, etc.), not just the text content.
*   **Improved UI Rendering:**
*   The `MarkdownOutputPanel` has been rewritten to render a sequence of distinct message components instead of a …
=> Refactor Output Handling to Use Structured Messages

src/main/java/io/github/jbellis/brokk/gui/Chrome.java, src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
Workspace is shown as un-editable when an older entry is selected in Activity history.
=> feat: Show Workspace as un-editable when clicking on older entries in Activity history

src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
Tested in several scenarios, including conflicts
https://github.com/user-attachments/assets/9cf11c08-a34b-450a-b5f8-06681a2a5e42
=> enh: Rename "Pop Stash" to "Apply and Remove" in GitLogTab

build.sbt, src/main/java/io/github/jbellis/brokk/GitHubAuth.java, src/main/java/io/github/jbellis/brokk/Project.java, src/main/java/io/github/jbellis/brokk/gui/AutoScalingHtmlPane.java, src/main/java/io/github/jbellis/brokk/gui/CheckThreadViolationRepaintManager.java, src/main/java/io/github/jbellis/brokk/gui/GfmRenderer.java, src/main/java/io/github/jbellis/brokk/gui/GitIssuesTab.java, src/main/java/io/github/jbellis/brokk/gui/GitPanel.java, src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java, src/main/java/io/github/jbellis/brokk/gui/GitUiUtil.java, src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java
Closes #67. Also closes #121, it was a small change and was easier to implement together to avoid conflicts as I refactored GitHub-related logic by extracting it in one place used by both PRs and Issues (and any other GitHub-related features in the future).
=> feat: GitHub Issues

src/main/java/io/github/jbellis/brokk/ContextManager.java, src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java, src/main/java/io/github/jbellis/brokk/gui/ManageSessionsDialog.java, src/main/java/io/github/jbellis/brokk/prompts/SummarizerPrompts.java
Took the approach to name the session after the first interaction. Since it is the summary of the same text as the task history entry in the activity log, just took that as the session name.
=> feat: Auto-rename Sessions

src/main/java/io/github/jbellis/brokk/difftool/doc/FileDocument.java
Fixes #100 
As expected this is a charset detection problem. Now we are checking for a confidence of detection higher than 50 or default to UTF-8
=> refactor: Improve charset detection and logging in FileDocument

src/main/java/io/github/jbellis/brokk/ContextManager.java, src/main/java/io/github/jbellis/brokk/GitHubAuth.java, src/main/java/io/github/jbellis/brokk/context/ContextFragment.java, src/main/java/io/github/jbellis/brokk/context/DtoMapper.java, src/main/java/io/github/jbellis/brokk/gui/Chrome.java, src/main/java/io/github/jbellis/brokk/gui/GitIssuesTab.java, src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java, src/main/java/io/github/jbellis/brokk/gui/mop/MarkdownOutputPanel.java, src/main/java/io/github/jbellis/brokk/gui/mop/stream/IncrementalBlockRenderer.java, src/main/java/io/github/jbellis/brokk/util/ImageUtil.java, src/main/java/io/github/jbellis/brokk/util/MarkdownImageParser.java, src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
This pull-request adds first-class support for capturing GitHub issues (including body, comments _and_ inline images) into the Brokk workspace, while tightening image/markdown handling, removing EDT violations and giving GUI renderers fine-grained control over HTML escaping.
Key themes
* Capture any GitHub issue from the new **Git Issues** tab into the workspace.
* Download and embed remote images (clipboard URL, issue body, comments) via a shared, authenticated `OkHttpClient`.
* Replace the ad-hoc `PasteImageFragment` with the more generic `AnonymousImageFragment`.
* Allow TaskFragments/Markdown renderers to opt-out of HTML escaping (needed for GitHub HTML in markdown).
* Fix several Swing thread-safety gaps.
* Centralise HTTP/image introspection in new `ImageUtil` & parsing in …
=> Capture Issues as Context

src/main/java/io/github/jbellis/brokk/gui/ProjectTree.java
updated right click behavior on the file tree to allow for right clicking on the row to activate the context dialog.
previously, you had to click on the file name specifically
=> fix: allow for right clicking on a file's row to activate context dialog

build.sbt, src/main/java/io/github/jbellis/brokk/Brokk.java
**Problem**  
Git operations over SSH fail (on my machine) with
```
publickey: no keys to try
```
because Apache MINA-SSHD (used by JGit 7.2.x) cannot find an `ED25519` signature implementation.  
Several “full” JDK builds on Ubuntu 25.04 (Oracle, Temurin, Corretto, etc.) also expose this gap, likely due to the way those packages are stripped or configured.
**Fix**  
1. Ship **Bouncy Castle** (`bcprov-jdk18on 1.80`) as a runtime dependency.  
2. Register the provider once at application start-up:
```java
static {
if (Security.getProvider("BC") == null)
Security.addProvider(new BouncyCastleProvider());
}
```
With BC present, MINA-SSHD successfully creates the `ssh-ed25519` signature and authentication works.
**Impact**  
• Pull / Fetch / Push now work
• No behaviour change on systems that …
=> feat: Add Bouncy Castle provider support for ssh (JGit)

src/main/java/io/github/jbellis/brokk/Brokk.java, src/main/java/io/github/jbellis/brokk/MainProject.java
This fix resides in loadRecentProjects(), and just checks to see if the projects we are showing still exist. This commit also includes a call to the function within Brokk.java to ensure the project files are loaded correctly even before UI is seen. I think that run is most likely not necessary in the vast majority of cases, but it may be important for some edge cases. If you'd like it removed, that is very easy to do.
=> fix/157 Added mechanism to prune deleted projects from recent project list

src/main/java/io/github/jbellis/brokk/gui/Chrome.java, src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
This pull request refactors the initialization of the `ThemeManager` and `commandInputOverlay` to ensure they are initialized correctly and consistently.
Key changes:
*   **ThemeManager Initialization:** The `initializeThemeManager()` method is moved to the `Chrome` constructor to ensure it's initialized before any other components that might depend on it. This ensures that the theme is loaded and applied as early as possible.
*   **commandInputOverlay Initialization:** The `commandInputOverlay` is initialized in the `InstructionsPanel` constructor. This ensures that the overlay is created and ready to be displayed when the panel is created.
*   **Overlay Cursor:** Sets the cursor of the `commandInputOverlay` to a text cursor to provide better visual feedback to the user.
These changes …
=> Refactors component initialization to avoid NPEs

src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
This pull request simplifies the handling of popup triggers within the `WorkspacePanel`.
*   **Intent:** The change aims to directly access the `tableScrollPane` instead of retrieving it from the `workspaceLayeredPane`.
*   **Behavior Changes:** The code now directly uses `tableScrollPane` to get the scroll pane for popup events. This avoids an unnecessary lookup within the layered pane.
*   **Implementation:** The code replaces `workspaceLayeredPane.getComponent(0)` with `tableScrollPane`. This makes the code more direct and potentially more efficient.
=> Fixes ClassCastException on WorkspacePanel

src/main/java/io/github/jbellis/brokk/git/GitRepo.java, src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
This pull request adds a "Fetch" button to the Git log tab, enabling users to fetch all remote changes.
Key changes:
*   **Fetch Button:** A new button is added to the UI to trigger a `git fetch --prune --all` operation.
*   **Background Task:** The fetch operation is executed in a background thread to prevent UI freezing.
*   **Progress Reporting:**  A `ProgressMonitor` implementation (`IoProgressMonitor`) is used to display fetch progress in the console.
*   **Error Handling:**  Basic error handling is implemented to display fetch failures in the console.
*   **UI Updates:** The UI is updated after the fetch completes to reflect the changes.
*   **`fetchAll` method:** A new method is added to `GitRepo` to fetch all remotes with pruning.
=> Adds a "Fetch" button to Git log, fetching remote changes in the background

src/main/java/io/github/jbellis/brokk/gui/CommitDialog.java
**Intent:** Enhance the CommitDialog GUI to provide better visibility into files being committed, helping users verify changes before finalizing a commit and reducing errors.
**Behavior Changes:** The dialog now features a horizontal split pane, displaying the commit message area on one side and a sorted list of files to commit on the other. This replaces the previous single-pane layout, allowing users to see file details (e.g., via tooltips) alongside the message input.
**Key Implementation Ideas:** 
- Used `JSplitPane` with a resize weight of 0.65 to allocate more space to the message area.
- Created a `JList` backed by a `DefaultListModel`, populated with sorted strings from `ProjectFile` objects.
- Added a labeled panel for the file list to clearly indicate the number of files …
=> Enhanced CommitDialog GUI: split pane for file visibility and commit message input (closes #356)

.idea/sbt.xml, src/main/java/io/github/jbellis/brokk/difftool/performance/PerformanceConstants.java, src/main/java/io/github/jbellis/brokk/difftool/scroll/ScrollDebouncer.java, src/main/java/io/github/jbellis/brokk/difftool/scroll/ScrollSyncState.java, src/main/java/io/github/jbellis/brokk/difftool/scroll/ScrollSynchronizer.java, src/main/java/io/github/jbellis/brokk/difftool/ui/DiffHighlightUtil.java, src/main/java/io/github/jbellis/brokk/difftool/ui/FilePanel.java, src/test/java/io/github/jbellis/brokk/difftool/scroll/ScrollDebouncerTest.java, src/test/java/io/github/jbellis/brokk/difftool/scroll/ScrollSyncStateTest.java, src/test/java/io/github/jbellis/brokk/difftool/scroll/ScrollSynchronizerTest.java, src/test/java/io/github/jbellis/brokk/difftool/ui/DiffHighlightUtilTest.java
I wasn't able to reproduce the bug on #391 but possible paths for it to happen were identified. Thus this PR focus on improving robustness
The code for diff highlighting and scrolling is asynchronous. To make testing easier some parts of the code were moved to separate classes that can be better tested without launching swing. some scenarios that could break painting were identified
A similar process was used to fix a few more issues related to scroll synchronization. I tested this with a file having many changes to be highlighted
fixes #391
=> General improvements to the diff panel

src/main/java/io/github/jbellis/brokk/MainProject.java, src/main/java/io/github/jbellis/brokk/gui/GitWorktreeTab.java, src/main/java/io/github/jbellis/brokk/gui/MergeBranchDialogPanel.java
**Intent:** Improve user experience in Git merge operations by remembering the last selected merge mode, reducing repetitive selections and making the workflow more efficient.
**Behavior Changes:** 
- The merge dialog now defaults to the previously used merge mode (e.g., MERGE_COMMIT) instead of always starting with a fixed option.
- Changes to the merge mode in the dialog are persisted immediately, so future sessions reflect the user's preference.
**Key Implementation Ideas:** 
- Added `getLastMergeMode` and `setLastMergeMode` methods in `MainProject.java` to store/retrieve the mode via workspace properties.
- In `GitWorktreeTab.java` and `MergeBranchDialogPanel.java`, integrated an ActionListener to save the selected mode on change, using Optional for safe handling of absent values.
(85 …
=> Remembers last Git merge mode, improving user experience and workflow efficiency

build.sbt, src/main/scala/io/github/jbellis/brokk/analyzer/builder/CpgBuilder.scala, src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/CBuilder.scala, src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/JavaSrcBuilder.scala, src/main/scala/io/joern/javasrc2cpg/util/Delombok.scala, src/main/scala/io/joern/x2cpg/passes/base/ContainsEdgePass.scala, src/main/scala/io/joern/x2cpg/passes/base/FileCreationPass.scala, src/main/scala/io/joern/x2cpg/passes/base/NamespaceCreator.scala, src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala, src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala, src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala
* Moves our overridden classes to the same path as where they would be in Joern, but these will be assembled first according to our merge strategy. The benefit is that if changes ever enter the dependency we have a clean refactor, as well as not carrying around duplicates of classes in the JAR.
* Adds the (modified) `Delombok` changes from https://github.com/joernio/joern/pull/5566 so that they take effect. The modification largely keeps things more "Scala"-like by instead instructing `.par` on which Executor to use.
* Upgrades Joern to a minimal version in order to be compatible with https://github.com/joernio/joern/pull/5566 
Resolves #407 (possibly?)
=> Override Joern Classes at Classpath Level

src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/CBuilder.scala, src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/cpp/PointerTypesPass.scala, src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala, src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/CallGraphTest.scala, src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/SimpleBuildTest.scala, src/test/scala/io/github/jbellis/brokk/analyzer/builder/javasrc/CallGraphTest.scala
Fixes bug by rewiring pointer types to their underlying types. This also required modifying the `DynamicCallGraphLinker` to traverse the graph instead of string properties.
Chained dynamically dispatched calls are also tested for Java and C++ now.
TLDR: Dynamic dispatch on C++ code works now
=> [C/C++] Pointer Parameter Linkage Bug Fix

src/main/java/io/github/jbellis/brokk/analyzer/Language.java
A regression was introduced by https://github.com/BrokkAi/brokk/commit/ea867b7f04f9a9c2679809c14816a3b994a13cf7#diff-7b73daccb7cf261e91d8e085a56d7fd4fc5d640d37896f3f3e9c82a98bcc4784L497-L498 which commented out the implementation for `getDependencyCandidates`. This has been rolled back
=> Reintroduced `TYPESCRIPT::getDependencyCandidates`

src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala
When resolving the parent of a lambda method, the function will traverse further up the AST before throwing an exception. Addresses the following exception
```
Exception in thread "DirectoryWatcher@36" flatgraph.SchemaViolationException: Unexpected node type class io.shiftleft.codepropertygraph.generated.nodes.TypeDecl encountered while resolving method name!
at io.github.jbellis.brokk.analyzer.JoernAnalyzer._parentMethodName$1(JoernAnalyzer.scala:156)
at io.github.jbellis.brokk.analyzer.JoernAnalyzer.parentMethodName(JoernAnalyzer.scala:167)
at io.github.jbellis.brokk.analyzer.JavaAnalyzer.parentMethodName(JavaAnalyzer.scala:105)
at io.github.jbellis.brokk.analyzer.JoernAnalyzer.getDeclarationsInFile$$anonfun$2$$anonfun$3(JoernAnalyzer.scala:1167)
at …
```
=> Make `JoernAnalyzer::parentMethodName` More Defensive

src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/PruneTypesPass.scala
Added check to only prune external types after incremental build. Might resolve https://github.com/BrokkAi/brokk/issues/485
=> Only Prune External Types

src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala, src/main/scala/io/joern/javasrc2cpg/astcreation/package.scala, src/test/resources/testcode-java/Interface.java, src/test/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzerTest.scala
Fixed bug where AST parents of lambda fields to interfaces returned a method, but it was an `<empty>` method that did not exist. These entries are filtered out.
Will merge when CI/CD green
=> Fixed `astParent` issue on interface field lambdas

src/main/scala/io/github/jbellis/brokk/analyzer/CppAnalyzer.scala, src/main/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzer.scala, src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala, src/main/scala/io/github/jbellis/brokk/analyzer/builder/IncrementalUtils.scala, src/main/scala/io/github/jbellis/brokk/analyzer/implicits/X2CpgConfigExt.scala
Incorporates the existing `updateFilesInternal` API to align with the `update` APIs where files are either given, or no files are given and the analyzer must determine changes.
Additionally, I updated comments to make it clear how this mechanism propagates into the Scala code.
=> Implement `update` APIs According to Specification

app/build.gradle.kts, joern-analyzers/build.gradle.kts, joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/IncrementalUtils.scala, joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/CBuilder.scala, joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/PruneTypesPass.scala, joern-analyzers/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala, joern-analyzers/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala, joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/IncrementalBuildTestFixture.scala, joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/IncrementalBuildTest.scala, joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/javasrc/IncrementalBuildTest.scala
When files are changed, and they are given to the analyzer, the analyzer assumed every other file was removed. However, these "removed" files are also not included from the subsequent rebuild, thus every other file was then pruned. This is fixed by adding every other path to the comparison that was not given by the file watcher.
Misc:
* Made it clear how the pruning works by separating query steps and adding comments
* Anonymous type decls on Joern `master` were being set as external types, this was fixed.
* Discovered that the C++ frontend did not respect the configured `defaultIgnoreRegex`. It is now patched.
* Configured Gradle to show exceptions in `joern-analyzers` for easier debugging
=> Fixed Accidental Pruning of Unchanged Files

app/src/main/java/io/github/jbellis/brokk/agents/BuildAgent.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/BlitzForgeDialog.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/BlitzForgeProgressDialog.java
**Intent:**  
This PR improves GUI responsiveness in the BlitzForge application by running potentially blocking operations, like determining and executing build verification commands, asynchronously to prevent UI freezes.
**Behavior Changes:**  
- Verification command checks in BlitzForgeDialog and BlitzForgeProgressDialog now run in the background using CompletableFuture, avoiding delays on the Event Dispatch Thread (EDT).  
- Post-processing logic dynamically enables/disables UI elements based on async results, ensuring the "Build First" checkbox reflects build availability without blocking user interactions.
- Added a new async method in BuildAgent (`determineVerificationCommandAsync`) to offload work to a background thread.  
- Utilized Java's …
=> Make BlitzForge* call BuildAgent outside the EDT

app/build.gradle.kts, app/src/main/java/io/github/jbellis/brokk/util/Decompiler.java, app/src/main/java/io/github/jbellis/brokk/util/MavenArtifactFetcher.java, build.gradle.kts, gradle/libs.versions.toml
This adds first-class support for importing original source code when a dependency’s *-sources.jar* is available and falls back to Fernflower decompilation only when necessary.
Key points
──────────
* build.gradle.kts – adds Maven Resolver dependencies required at runtime
* MavenArtifactFetcher – lightweight façade around Eclipse Aether • resolves <groupId>:<artifactId>:<version>[:classifier] to a local file • logs transfer progress and failures
* Decompiler • extracts Maven coordinates from pom.properties • tries sibling *-sources.jar* in same directory • otherwise uses MavenArtifactFetcher to pull sources from Central • cleans up temp dirs; prompts before overwriting existing dependency dir
* Thorough logging of every branch (download, unpack, decompile)
House-keeping
─────────────
* …
=> feat(import): auto-download sources JARs on dependency import (fallback to Fernflower)

app/src/main/java/io/github/jbellis/brokk/gui/components/SplitButton.java
FlatLaf’s `BoxLayout` occasionally shrank `SplitButton` below the space needed for its text because `getMinimumSize()` and `getMaximumSize()` dropped the arrow-section width whenever a preferred size had been set. This caused the arrow area to overpaint the label (see screenshot in #446).
The new logic unconditionally adds `ARROW_WIDTH` unless the caller has explicitly set a *minimum* or *maximum* size, bringing the button’s size contract in line with what it actually paints.
Limitation: if the user resizes the *entire* application window to an extremely small width, upstream layout managers may still violate the button’s minimum size, so labels can disappear. That trade-off is considered acceptable for now and matches typical Swing behaviour.
=> enh/SplitButton: always include arrow width in min/max size (fixes #446)

app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java, app/src/main/java/io/github/jbellis/brokk/gui/GitHistoryTab.java, app/src/test/java/io/github/jbellis/brokk/git/GitRepoFileHistoryTest.java
**Intent:**  
This PR enhances the Git integration to accurately track and display file history across renames, improving the GUI's ability to show the correct file paths for each commit. This helps users navigate file changes more effectively, especially in scenarios involving file renames.
Fixes #552 
**Behavior Changes:**  
- The `GitRepo` class now includes a new method, `getFileHistoryWithPaths`, which returns commit history along with the file's path at each commit, following renames backwards.  
- In `GitHistoryTab`, the history table incorporates per-commit paths (stored but hidden), and context menu actions (e.g., viewing diffs or editing) use these paths, ensuring actions reference the correct historical file location.
- Leverages JGit's …
=> Enhanced Git file history: accurate paths, rename tracking

app/src/main/java/io/github/jbellis/brokk/ContextManager.java, app/src/main/java/io/github/jbellis/brokk/context/ContextHistory.java, app/src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
- Moved `liveContext` to `ContextHistory`.
- Using a new `ContextHistory` instance instead of mutating existing one when changing sessions.
We should also probably revisit the logic related to `pushContext` in `ContextManager` to confirm that no race conditions exist there, but it will be a bit easier to follow up and improve that now too if needed.
=> refactor: fix race conditions with liveContext in ContextManager

gradle/wrapper/gradle-wrapper.properties
This upgrade is to support JDK24. The following warning is now issued, however.
```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/Users/dave/.gradle/wrapper/dists/gradle-8.14-bin/38aieal9i53h9rfe7vjup95b9/gradle-8.14/lib/native-platform-0.22-milestone-28.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```
=> Upgrade Gradle 8.13 -> 8.14

app/src/main/java/io/github/jbellis/brokk/MainProject.java, app/src/main/java/io/github/jbellis/brokk/agents/ArchitectAgent.java, app/src/main/java/io/github/jbellis/brokk/agents/CodeAgent.java, app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java, app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/BlitzForgeProgressDialog.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsProjectPanel.java, app/src/main/java/io/github/jbellis/brokk/util/Environment.java, app/src/test/java/io/github/jbellis/brokk/agents/CodeAgentTest.java, app/src/test/java/io/github/jbellis/brokk/git/GitRepoTest.java, app/src/test/java/io/github/jbellis/brokk/util/EnvironmentTest.java
Fixes #587, uses different timeouts for different actions
Key changes:
*   **Shell Command Timeouts:** Added a timeout for shell commands, defaulting to 2 minutes. 
*   **Git Command Timeouts:**  Added specific timeouts for Git commands: 10 seconds for fast commands and 5 minutes for network-heavy operations.
*   **Project Settings:** Added a new setting in the project settings dialog to configure the build command timeout.
*   **Git Worktree Operations:** Improved error handling and added a timeout to Git worktree operations.
*   **Test Updates:** Added tests to verify the new timeout functionality and ensure that negative timeouts are handled correctly.
=> subprocess timeout

app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java, app/src/test/java/io/github/jbellis/brokk/GitProjectStateRestorerTest.java, app/src/test/java/io/github/jbellis/brokk/git/GitRepoMergeConflictTest.java, app/src/test/java/io/github/jbellis/brokk/git/GitRepoRemoteMergeTest.java, gradle/libs.versions.toml
Fixes the issue where commits cannot be made via Git since GPG signing is currently unsupported. As someone who has GPG signing enabled globally, this is fairly important, and also currently fails my Brokk test suite.
Fixing the bug by simply letting unsigned commits is one thing, but supporting GPG signing is a much larger effort, so this is not attempted here. There is a placeholder for keeping the passphrase, but this is what we will need from the user in order to sign commits.
See https://github.com/BrokkAi/brokk/issues/98
=> Disable GPG Signing if Enabled in Config

app/src/main/java/io/github/jbellis/brokk/ContextManager.java, app/src/main/java/io/github/jbellis/brokk/context/ContextHistory.java, app/src/main/java/io/github/jbellis/brokk/difftool/doc/AbstractBufferDocument.java, app/src/main/java/io/github/jbellis/brokk/difftool/doc/BufferDocumentIF.java, app/src/main/java/io/github/jbellis/brokk/difftool/scroll/DiffScrollComponent.java, app/src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java, app/src/main/java/io/github/jbellis/brokk/difftool/ui/BufferDiffPanel.java, app/src/main/java/io/github/jbellis/brokk/difftool/ui/ChunkApplicationEdit.java, app/src/main/java/io/github/jbellis/brokk/difftool/ui/FilePanel.java, app/src/test/java/io/github/jbellis/brokk/difftool/ui/ChunkApplicationEditStateTest.java, app/src/test/java/io/github/jbellis/brokk/difftool/ui/DiffPanelUndoIntegrationTest.java
This pull request fixes #529, now chunks are not autosaved, instead we save with the general save button. also saves are recorded on the history and can be undone.
This was a tough nut to crack especially with undo, I tried to make it behave as editing on preview works
I may do a refactor later on as the diff related classes are getting fairly big
Key changes:
*   **Improved Undo/Redo for Chunk Operations:** The `ChunkApplicationEdit` class is introduced to manage the undo/redo operations for applying or deleting diff chunks. This ensures that both the document content and the patch state are correctly restored during undo/redo.
*   **Immediate History Creation:** The code now captures the original content of a file *before* a diff chunk is applied. This allows for immediate undo/redo of …
=> Improve diff save and include in history

app/src/main/java/io/github/jbellis/brokk/gui/mop/webview/MOPWebViewHost.java
fixes #619
- Intent: disable the built-in JavaFX/WebKit right-click context menu for the embedded MOP WebView so the app can control or suppress context interactions (e.g., provide a custom menu or prevent copy/paste/web actions).
- Behaviour change: the WebView will no longer show the default browser-like context menu on right-click. This reduces unexpected UI from the web engine and avoids exposing web-specific actions to users.
- Implementation: immediately after creating the WebView on the JavaFX thread (Platform.runLater), call view.setContextMenuEnabled(false). The reference storing and Scene setup are unchanged, so existing theme updates and scene wiring continue to work.
=> Disables WebView's context menu using `setContextMenuEnabled(false)` for custom control

app/src/test/java/io/github/jbellis/brokk/difftool/scroll/ScrollFrameThrottlerTest.java
While these errors occur on the MacOS runner, it happens less so. We can disable this on MacOS if it happens often but for now I suggest we keep it enabled.
=> Disable `ScrollFrameThrottlerTest` on Windows

app/src/main/java/io/github/jbellis/brokk/ContextManager.java
Closes #633.
It seems that `createSessionFromContextAsync` relies on GUI to be set up (sets the current context history, notifies listeners, etc), while `createSessionWithoutGui` synchronously creates the session that is later to be picked up in the initialization as the active session. So fixed by just unfreezing the context in `createSessionWithoutGui` too, to make it work without any refactoring for now.
=> fix: AssertionError on worktree with copying session

app/src/main/java/io/github/jbellis/brokk/agents/ContextAgent.java
If duplicate files are given to `ContextAgent.readFileContents` then the line `.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));` may throw an exception as it does not expect duplicate keys.
=> Fix: Deduplicate Files before Reading

app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
Tested on both `master` and `0.13`:
* Fixes issue where `file` in the popup was `null` during preview
* Prevents duplicate unit actions being populated
* In the case of `master`, where constructors share the name of the type`, special deduplication handling is added.
* (Optional) Made the shortname render within `<code>` blocks. If this is irritating to look at, it can easily be rolled back.
Note: Merging this into 0.13 as it fixes some bugs.
Related to https://github.com/BrokkAi/brokk/issues/686
=> Fix Duplicate Actions in File Preview

app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java, app/src/test/resources/testcode-java/A.java
Modified `createPopupMenu` to capture the exact token where possible, or use the full line as fallback. This results in much more precise `CodeUnit` matches. If this token matches, it is used in the menu as the identifier. 
The reason why records and nested classes were not being populated is because their `shortName()` contained the parent class separated by the `$` symbol. This approach ensures we only consider the simple identifier as far as possible.
Examples
Fixed bug where `no usages == definition not found` and an exception was thrown in JdtAnalyzer.
=> File Preview Captures Exact Token

app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
=> enh: Render StringFragment, PasteFragment with MarkdownOutputPanel if their syntaxStyle = SyntaxConstants.SYNTAX_STYLE_MARKDOWN

app/src/main/java/io/github/jbellis/brokk/agents/ContextAgent.java
It was discovered that the LLM may suggest duplicate file paths. This may cause issues down the line. This fix deduplicates the suggested objects in the `LlmRecommendation` constructor.
=> Deduplicate LLM Recommendation

app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Similar to what one can do in VSCode and IntelliJ, clicking on a side tab icon that is already open would minimize the side tab. This is also "remembered" when re-opening the IDE as the tab width would be 0 on startup and detected accordingly as "minimised".
https://github.com/user-attachments/assets/69991396-e1eb-46a1-bf0a-af1c1eb1d72e
=> Minimize Side Tabs on Click

app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
Checks if the analyser for the current file supports capturing usages/source code before enabling the option. If disabled, offers a tooltip to explain why feature is missing.
=> Check Analyser Capabilities Before Offering Capture Option

analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/UsagesProvider.java, app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java, app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspLanguageClient.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
* `LspAnalyzer` attempts to find the "container" and descend into members if no `fqName` hit returns any results.
* Including constants as "field-likes" as these are what static fields are classified as.
* Usages on PreviewTextPanel now give `fqName`.
=> `LspAnalyzer`: Enable Field Support on `getUses`

app/src/main/java/io/github/jbellis/brokk/Brokk.java, app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Converts the generic "white" title bar on macOS to be themed by using the full height of the content window, and inserting a JLabel in order to obtain a fully themed window.
This does not affect dialogs, only JFrames.
=> macOS: Themed Title Bar

app/src/main/java/io/github/jbellis/brokk/agents/SearchAgent.java
fixes #789 
Resolves an issue where the Search Agent would fail silently after the LLM merged multiple tool names into a single, invalid call (e.g., toolAtoolB).
The prompt ambiguously encouraged invoking tools "at once," which the LLM misinterpreted. This change clarifies the instruction, explicitly telling the model to provide a list of separate tool calls. This prevents malformed requests, ensures correct tool execution, and improves agent reliability when planning multiple actions in a single turn.
=> fix(SearchAgent): Clarify prompt to prevent merged tool calls

app/src/main/java/io/github/jbellis/brokk/Completions.java, app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java, app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
Partially resolves https://github.com/BrokkAi/brokk/issues/700#issuecomment-3233242983
The edited test cases largely roll back the added "child" results and are passing. I am seeing completions coming up nicely again
=> Rolls back "getChildren" component of completions

app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java, app/src/main/java/io/github/jbellis/brokk/git/GitDistance.java, app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistanceMostImportantTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistancePMITest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistanceTestSuite.java, app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/TestProjectWithRepo.java
Introduced a new method, `GitDistance.getMostImportantFiles`, to identify the most significant files in a repository. This method provides a way to rank files without requiring any seed files as input.
The method implements an exponential decay algorithm to score files based on their commit history. Changes in recent commits are weighted more heavily than older ones, ensuring the ranking reflects current development activity rather than just the total number of changes over time.
=> GitDistance: Most Important Files

app/src/main/java/io/github/jbellis/brokk/context/ContextHistory.java, app/src/main/java/io/github/jbellis/brokk/context/DtoMapper.java, app/src/main/java/io/github/jbellis/brokk/context/FragmentDtos.java, app/src/main/java/io/github/jbellis/brokk/gui/GitCommitTab.java, app/src/main/java/io/github/jbellis/brokk/gui/ProjectTree.java, app/src/main/java/io/github/jbellis/brokk/util/HistoryIo.java
Closes #415:
- Operation is added to context history and can be undone/redone.
- Deleted tracked files are also git-removed, untracked ones are just deleted. The same behavior for redo.
- Deleted tracked files are git-added on undo, deleted untracked ones are just restored.
=> enh: Add "Delete File" option in file tree

app/src/main/java/io/github/jbellis/brokk/Llm.java, app/src/main/java/io/github/jbellis/brokk/Service.java
Updated timeouts (reset when we get either a thinking or output token):
- 2m for the first token
- 1m for every next token
- 15m for first and next token for `flex` service tier.
I did not change the [retry](https://github.com/BrokkAi/brokk/blob/f26d016d28517e932f60ad0ea41c4d53ce043d1b/app/src/main/java/io/github/jbellis/brokk/Llm.java#L74) logic with backoff time here, so when a timeout happens, we'd still retry.
=> enh: update Llm timeouts for thinking models

analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/Completions.java, app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java, app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java, app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerSearchTest.java, app/src/test/java/io/github/jbellis/brokk/testutil/MockAnalyzer.java
Take 3 or 4 of trying to solve the auto-complete issue. This change focuses on `TreeSitterAnalyzer`. 
This approach tries something new, that is, using a navigable set structure to find initial auto-complete candidates. It involves introducing a new global data structure which is not ideal, but further makes the case for something like Chronicle map/ a database down the line.
This is backed by a skip list and provides us with `NavigableSet` methods like `tailSet` which are used if possible to speed up prefix-based queries. Other queries that are more camel-case or hierarchical leverage a more expensive, O(N), strategy.
Symbols are also cached to matching code units for fast lookups.
In terms of testing, this also tests against the `JavaAnalyzer` to get more of an integration test and view …
=> Separated Completion Task from Wrangling `searchDefinitions` to Dedicated `autocompleteDefinitions`

app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
* Items are now fetched on drop-down click to ensure latest items are always available
* Truncation is re-introduced via dynamically obtaining the width of the combo box as the width reference (still no hardcoded variable)
* Latest items are on the top, but this was already the case.
=> History Fetches Latest Items on Dropdown + Dynamic Truncation

app/src/main/java/io/github/jbellis/brokk/gui/GitCommitTab.java, app/src/main/java/io/github/jbellis/brokk/gui/components/ResponsiveButtonPanel.java
* Introduced `ResponsiveButtonPanel` to manage keeping buttons visible when viewport shrinks horizontally.
* Wrapped button text in HTML to ensure text can break and button width can shrink if necessary
https://github.com/user-attachments/assets/f93c7f21-00ca-4fdc-bd3e-c057e20ece87
=> Enforce Buttons are Present in Commit Tab

app/src/main/java/io/github/jbellis/brokk/ContextManager.java, app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java, app/src/main/java/io/github/jbellis/brokk/gui/mop/MarkdownOutputPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/mop/webview/MOPBridge.java, app/src/main/java/io/github/jbellis/brokk/gui/mop/webview/MOPWebViewHost.java, frontend-mop/src/components/CopyablePre.svelte, frontend-mop/src/global.d.ts
fixes #173
- Intent: allow users to capture code/text blocks from the MOP view into the workspace as a virtual pasted-text fragment, with an asynchronous summarization task attached and immediate UI feedback.
- Behaviour changes:
- Adds a "Capture" button to code blocks in the MOP frontend. Clicking it calls the Java bridge and shows transient "Captured" feedback.
- Captured text is submitted to the ContextManager which creates a PasteTextFragment and schedules background summarization.
- WorkspacePanel no longer duplicates summary submission; it delegates to ContextManager.addPastedTextFragment.
- Accessibility: ARIA/role/status updated to announce capture events.
- Key implementation notes:
- New ContextManager.addPastedTextFragment(text) submits the summarization Future and adds a …
=> Feat: Adds "Capture" button to MOP, captures text, summarizes, and adds UI feedback

app/src/main/java/io/github/jbellis/brokk/util/Messages.java
Closes #860:
- ~~Removed reasoning content from `Messages.getText`.~~ Return text if present, otherwise return reasoning.
- Added both in `getRepr`: if there is reasoning, we add `Reasoning:` and `Text:` headers, otherwise we keep the old behavior with text content without header (with optional tool calls).
=> fix reasoning treatment in Messages.getText

app/src/main/java/io/github/jbellis/brokk/ContextManager.java, app/src/main/java/io/github/jbellis/brokk/context/ContextFragment.java, app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SymbolSelectionDialog.java
* Usages dialog includes an unchecked tickbox to include test code
* Modified selection dialog to use a record to contain selection information
* UsageFragment filters out test files on various getters based on the `includeTestFiles` field
* To test: Choose something widely used like `CodeUnit.fqName` to illustrate difference.
=> Ignored-by-default Test Code Checkbox in Usage Dialog

app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Adds a mouse listener to add back behaviour expected of a title bar on macOS
=> Double Click Title Bar Maximize/Normal Functionality

app/src/main/java/io/github/jbellis/brokk/context/FrozenFragment.java, app/src/test/java/io/github/jbellis/brokk/SessionManagerTest.java, app/src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
Closes #848: Extracted `SessionManager`-related tests from `ContextSerializationTest` into `SessionManagerTest`.
=> refactor: Extract SessionManager tests

app/src/main/java/io/github/jbellis/brokk/analyzer/JavaAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java
Found that JavaAnalyzer would only call update for one of the analysers, causing weird behaviour:
* The return value of `update` is the analyser itself, thus if the return value of the JdtAnalyzer is used, the JavaAnalyzer "disappears" during the update and the current analyser becomes the JdtAnalyzer
* If only one analyser updates, then only one analyser has the current state.
This fixes both issues, and confirms what I've observed in the `update` being a bit buggy for some reason (though I attributed this to some `isCpg` checks).
=> Fix JavaAnalyzer Logic on Update

app/src/main/java/io/github/jbellis/brokk/analyzer/NodeJsDependencyHelper.java, app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesPanel.java
fixes #1002 
Fixes npm scoped dependencies being collapsed under a single @scope entry in the Dependencies table.
Ensures the UI shows the original package name with version using the common format name@version (e.g., @angular/material@19.2.5).
Stores imported Node packages under a flat, sanitized folder name where “/” is replaced with “__” (e.g., @angular__material@19.2.5) to avoid nested directories.
Import: Target folder name is derived from package.json’s name and version as name@version, replacing “/” with “__”.
Display: Dependencies table now reads package.json from each imported folder and uses name@version for the display name. Falls back to the folder name if package.json is missing/unreadable.
Previously, scoped packages imported into nested directories (e.g., …
=> feat: Node dependency display and storage improvements: "name@version" format, safe folder names

app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java, app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java, app/src/main/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzer.java, app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerSearchTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/PythonAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/testutil/MockAnalyzer.java
A problem with using the `$` separators is that JDT does not use them. It is easy to map from TreeSitter names that have dollar signs, but not the other way around due to loss of precision in the name.
This may mean that any `fqNames` from JDT referring to nested classes cannot be resolved in TreeSitter-based analysers.
This PR ensures TreeSitter analyzers use `.` separators for inner classes to be consistent with JDT's naming scheme. This simplifies a few checks elsewhere too.
=> Normalize `$` Class Separators as `.`

frontend-mop/src/components/EditBlock.svelte, frontend-mop/src/components/ThreadBlock.svelte, frontend-mop/src/styles/global.scss, frontend-mop/src/worker/rehype/rehype-edit-diff.ts, frontend-mop/src/worker/shared.d.ts
- Intent: surface edit/diff metrics in thread headers (collapsed history entries) and centralize diff color tokens for theming. Also propagate per-bubble diff summaries from the rehype pipeline so the UI can aggregate them for the edit metrics.
---
Now the history works like that:
1. In the main MOP you see the tasks in the history collapsed at the top
a. you see the edits, message count and lines for each task
b. the copy + capture button (below the main MOP) is scoped to the current task and ignoring the history tasks
2. If you open the history entry (from the workspace; i.e. with double-click), you see
a. the whole history in one node (expanded by default)
b. collapsing shows the all edits, message count and lines for the whole history (from all tasks) => [around 600 LOCs ~ 664 LOC …
=> feat: history entries in MOP shows edit metrics and line count

app/src/main/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java, app/src/main/resources/treesitter/java.scm, app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java, app/src/test/resources/testcode-java/A.java, app/src/test/resources/testcode-java/EnumClass.java
* Fix issue where `TreeSitterAnalyzer` function skeleton building ignored modifiers
* Included special handling for enum constant skeleton building and fixed tree sitter query to match expectations
* Updated unit tests to verify behaviour
Example summary:
=> Fix Missing Java Enum Constants & Method Modifiers

app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesPanel.java
- prevent changes to the dependencies panel until the save is completed, the rest of the UI is accessible. This keeps the state in sync or at least more in sync than it was
- not the greatest user experience, but I am not sure how to solve this beyond batching ie going back to a check a bunch and then click save, but then we have to deal with how to prevent users from doing anything without realizing they're saved. I think this gets us through for now, but we are going to have to do a bigger deep dive into how we load and unload these and if we can do them in a way that is more concurrency friendly.
=> 997 bug dependencies are racy

app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspLanguageClient.java, app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspServer.java
* The settle delay before waiting for all diagnostics to come in is increased by 1 second to try sync with the LSP server. Ultimately, this is where the flakiness comes from as diagnostics are sent without an indication of "are there more coming?". Slower machines, such as CI/CD runners may need more grace.
* Improved normalisation of paths and URIs in diagnostics to attempt to resolve the issue in the stack trace of https://github.com/BrokkAi/brokk/issues/1109
=> Increase Linting Settle Delay + Improved Path Normalisation in Diagnostics

app/src/main/java/io/github/jbellis/brokk/analyzer/Language.java
Due to performance improvements and much more liberal multi-threading from https://github.com/BrokkAi/brokk/commit/0887c4e37b04d55f19ddf77b967feff1b83321b8, it makes sense to keep these analyzer creations in serial to avoid overloading the system with threads/thread pools
=> Revert Back to Serial Analyzer Creation

frontend-mop/src/lib/edit-block/fenced-edit-block.ts, frontend-mop/src/lib/edit-block/tokenizer/fence-open.ts, frontend-mop/src/lib/edit-block/tokenizer/filename.ts
fixes #861
- Intent: be more lenient about small formatting variations after a fenced edit-block opener and support filename declarations on the next line that are prefixed by a comment marker (//). This improves robustness for authors who add a space/tab after the fence or put a filename on the next line as a comment.
- Behaviour changes:
- Accepts optional horizontal whitespace (space or tab) immediately after the opening fence instead of rejecting it.
- Removes the previous eager rejection in the fence-open tokenizer for a space/tab after the fence.
- Allows a next-line filename prefixed with "//" (optionally followed by a single space). If the line is only "//" (no filename), it is treated as absent and header parsing proceeds.
- Inline filename parsing (same-line as fence) remains …
=> Improved fenced edit-block parsing: whitespace tolerance, comment-prefixed filenames, robustness

app/src/main/java/io/github/jbellis/brokk/analyzer/CodeUnitProperties.java, app/src/main/java/io/github/jbellis/brokk/analyzer/CppTreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/FileProperties.java, app/src/main/java/io/github/jbellis/brokk/analyzer/PhpAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzer.java, app/src/main/java/io/github/jbellis/brokk/analyzer/cpp/NamespaceProcessor.java, app/src/test/java/io/github/jbellis/brokk/analyzer/CSharpAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/GoAnalyzerTest.java, app/src/test/java/io/github/jbellis/brokk/analyzer/PythonAnalyzerTest.java
* Merged maps with shared `CodeUnits` into a map to `CodeUnitProperties`. A similar task was performed for `ProjectFile`.
* Created accessor methods to more easily get a property for a given key, e.g., `childrenOf(CodeUnit)` or `topLevelCodeUnitsOf(ProjectFile)`
* Removed some unused functions, made usages of accessors more consistent, deduplicated some logic
The result is that we have 1 parse tree cache map, 1 symbol index map, and 2 maps for code unit properties and project file properties.
=> Merge TreeSitterAnalyzer Maps

app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java, app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/git/GitLogTab.java
- Use abbreviated commit IDs for detached HEAD displays: GitRepo now tries to abbreviate the head object via an ObjectReader and falls back to the full SHA on IO errors.
- Wire up the branch selector as a persistent field and add robust UI refresh logic: InstructionsPanel now stores branchSplitButton, adds refreshBranchUi(...) and updateProjectFilesDrawerTitle(...) helpers that run on the EDT, update the branch label, update the Project Files drawer title (via GitUiUtil), and trigger Git log refresh/selection.
- Improve branch menu handling: separate local branch listing, iterate local branches for the dropdown, and safely show popups with a requireNonNull check.
- Better remote-branch checkout handling in GitLogTab: if the requested branch is not local, treat remote refs as tracking …
=> Bug/sync branch visuals between project drawer, gitlog tab, and branch selector in instructions panel

app/src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java, frontend-mop/src/components/ThreadBlock.svelte, frontend-mop/src/components/ThreadMeta.svelte, frontend-mop/src/stores/historyStore.ts, frontend-mop/src/styles/global.scss, frontend-mop/src/types.ts
fixes #1192
- Intent: improve copy/delete UX for conversation threads and align the desktop "copy" button with workspace context handling; refactor thread metadata into a reusable component and harden reasoning flags handling.
- Behaviour changes:
- Desktop copy button now copies the most recent HISTORY fragment from the selected workspace via performContextActionAsync(COPY) and reports when no context/history exists.
- Thread UI gains a reusable ThreadMeta component used both in the header and inline overlay; it exposes copy and delete buttons, with a brief "copied" visual feedback.
- Frontend copy produces an XML representation of the thread and writes to the clipboard with a navigator.clipboard path and a textarea fallback.
- Message reasoning flags are normalized to boolean in the …
=> feat: add copy button for each task (MOP); button under MOP copies all (task + history)

app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SessionsDialog.java
- Add a searchable, debounced session search to the Sessions dialog UI.
- Behavior: a new LoadingTextBox appears above the sessions table; typing filters sessions by name (case-insensitive, Locale.ROOT). Filtering is debounced (300 ms) so the table isn’t refreshed on every keystroke.
- Key implementation points:
- Added LoadingTextBox searchBox and a Swing Timer (SEARCH_DEBOUNCE_DELAY = 300) to SessionsDialog.
- Hooked a DocumentListener on the search box that restarts the timer; when the timer fires it calls refreshSessionsTable().
- The session-list population now reads searchBox.getText(), lowercases with Locale.ROOT, and filters SessionInfo.name() before sorting and showing results.
- Minor imports and fields added; UI layout places the search box at the top of the sessions panel.
- …
=> feat: Added debounced session search to Sessions dialog

app/src/main/java/io/github/jbellis/brokk/Service.java
This streamlines integration and development with the whole webapp stack locally.
=> fix: send a fixed user parameter when connected LOCALHOST

app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
- Intent: Allow combining more than two tasks at once (previously limited to exactly two) and update UI/validation to reflect that capability.
- Behaviour changes:
- Combine button now enabled when 2 or more tasks are selected (and edits aren’t blocked).
- Tooltip and validation messages updated to say “at least two” / “2 or more”.
- When combining multiple tasks, their texts are merged with " | " separators; the resulting task is marked done if any of the originals were done.
- The combined task replaces the first selected task; the other selected tasks are removed.
- Key implementation notes:
- Selection indices are sorted and validated; null/invalid entries are skipped.
- Collected texts are joined via String.join; done state is computed by OR-ing original done flags.
- Removals are …
=> Allows combining multiple tasks, updates UI, merges texts, and manages done states

.brokk/style.md, app/src/main/java/io/github/jbellis/brokk/ContextManager.java, app/src/main/java/io/github/jbellis/brokk/IContextManager.java, app/src/main/java/io/github/jbellis/brokk/agents/SearchAgent.java, app/src/main/java/io/github/jbellis/brokk/context/ContextFragment.java, app/src/main/java/io/github/jbellis/brokk/context/DtoMapper.java, app/src/main/java/io/github/jbellis/brokk/tools/SearchTools.java, app/src/main/java/io/github/jbellis/brokk/tools/WorkspaceTools.java, app/src/main/java/io/github/jbellis/brokk/util/HistoryIo.java, app/src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java
- Intent: migrate build-results and workspace-note handling to unified, describable StringFragments; add an append-note tool and persist discard explanations; simplify SearchAgent by removing duplicate-forging/tracking logic; remove one style rule.
- Behavior changes:
- Build output is no longer a special BuildFragment; it’s stored/queried as a StringFragment with description "Latest Build Results" (backwards-compatible DTO conversion preserved).
- New Task Notes (SEARCH_NOTES) StringFragment and a DISCARDED_CONTEXT StringFragment type are added.
- New SearchTools.appendNote(markdown) appends or creates Task Notes in the workspace.
- WorkspaceTools.dropWorkspaceFragments now accepts a map {fragmentId -> explanation}, removes fragments, and records/merges explanations into …
=> Improved SearchAgent tools

.github/workflows/release.yml, app/src/main/java/io/github/jbellis/brokk/gui/util/JDeploySettingsUtil.java, app/src/test/java/io/github/jbellis/brokk/gui/util/JDeploySettingsUtilTest.java, package.json
- Update jDeploy to 5.2.1 in release workflow
- Specify runtime config file to be used by jDeploy launcher at `~/.config/brokk/jdeploy.json`
- Changed JDeploySettingsUtil to update the new runtime config file.
- Added unit test for JDeploySettingsUtil
This resolves a few issues:
- https://github.com/BrokkAi/brokk/issues/944
- https://github.com/BrokkAi/brokk/issues/1092
- https://github.com/BrokkAi/brokk/issues/1216
=> fix: Make max memory configurable at runtime in jDeploy

app/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java, app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
If the query to `IAnalyzer.autocompleteDefinitions` is shorter than 5 characters, this adds an additional query to `searchDefinitions` comprising adding wildcards between characters for a case-insensitive search, e.g., `cc` becomes `(?i).*c.*c.*`.
This should provide sufficient candidates for the FuzzyMatcher to later use the camel-case heuristic on. This is not necessarily performant, but TreeSitterAnalyzer does override this with a more performant approach.
=> Default `autocompleteDefinitions` Overapproximates for Possible Acronyms

app/src/main/java/io/github/jbellis/brokk/gui/git/GitCommitTab.java, app/src/main/java/io/github/jbellis/brokk/gui/util/GitUiUtil.java
Closes #1201: 
I fixed it for read-only git operations (view diff or file at revision, etc) for now, because when there is an llm task in progress, code changes might be happening at that time (though e.g. commit would probably not do any harm, but we could end up committing partial changes and similar). 
I thought about distinguishing Ask vs Code, but then Ask logic might be part of architect task and/or do code search, so I didn't want to go there without broader discussion for now.
=> fix: [Bug]: Cannot look at git diff and do a git commit with the output window is running

app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java, app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/WorkspaceItemsChipPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java, app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesDrawerPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesPanel.java, app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ImportDependencyDialog.java, app/src/main/java/io/github/jbellis/brokk/gui/util/ContextMenuUtils.java
- We now have collapsed workspace that remembers if it was collapsed between restarts
- mini-workspace underneath the instructions box, this replaces the old suggestions code. It is not fully complete yet (colors I don't like, I have not added the right clicks cause I think we don't need them, and I havent removed the old drag and drop behavior because I want feedback first) but I think it is ready to use and get feedback. It does have, add, remove, mouse over loc and tokens per file, mouse over files in summary, ability to click and preview and it has support for drag and drop.
- dependencies is a button and a dialog now, I will do a second pass and add a badge, but every time I do that it is a time sink and this was a big enough PR
- final bit the story isnt great yet if the workspace …
=> Move workspace into instructions
